#language: objective-c
#xcode_project: Games/Games.xcodeproj # path to your xcodeproj folder
#xcode_scheme: Games
#osx_image: xcode9.2

sudo: required
dist: trusty
language: generic
services:
  - docker

before_install:
  - docker build -t chuckhays/swiftgames .

script:
  - docker run -w /build --privileged chuckhays/swiftgames TicTacToe/build.sh 

